import { CITY_STAY_MATCHER_AFFILIATE_LINKS } from "@/lib/affiliateLinks";
import type { CityMatcherConfig, CityMatcherSeasonalReference } from "@/components/CityStayMatcher";

const standardSeason = (city: string): CityMatcherSeasonalReference => ({ label: `${city} shoulder-season reference`, multiplier: [1, 1], note: "This guide uses its published typical shoulder-season planning range as the reference." });

export const bangkokStayMatcherConfig: CityMatcherConfig = {
  id: "bangkok", city: "Bangkok", articleUrl: "/blog/where-to-stay-in-bangkok-2026", availabilityUrl: CITY_STAY_MATCHER_AFFILIATE_LINKS.bangkok, supportsTierEstimates: true,
  seasonal: (date) => [0, 1, 10, 11].includes(Number(date.slice(5, 7)) - 1)
    ? { label: "Bangkok busy-season reference", multiplier: [1.15, 1.3], note: "The guide notes that November to February can run 15–30% higher than typical shoulder-season ranges." }
    : standardSeason("Bangkok"),
  questions: [
    { field: "vibe", label: "What should shape your first Bangkok stay?", options: [{ value: "transit", label: "Easy BTS/MRT access and city-wide flexibility" }, { value: "temples", label: "Temples, river views and sightseeing" }, { value: "nightlife", label: "Dining, markets and nightlife" }, { value: "calm", label: "A quieter base for a longer stay" }] },
    { field: "budget", label: "What is your typical nightly budget approach?", options: [{ value: "budget", label: "Budget-led planning" }, { value: "mid", label: "Mid-range comfort" }, { value: "luxury", label: "A special hotel or luxury stay" }] },
    { field: "duration", label: "How long are you likely to stay in Bangkok?", options: [{ value: "short", label: "1–3 days" }, { value: "medium", label: "4–7 days" }, { value: "long", label: "8+ days" }] },
  ],
  areas: [
    { key: "sukhumvit", name: "Sukhumvit", anchor: "#sukhumvit", heading: "BTS access, dining and nightlife", summary: "A flexible first-timer base along the Skytrain with a wide hotel choice, dining, shopping, and nightlife within easy reach.", highlights: ["BTS Skytrain access", "Dining and malls", "Thonglor and Ekkamai nightlife"], location: "Central east Bangkok", locationContext: "Sukhumvit runs along Bangkok’s eastern central corridor and is anchored by frequent BTS Skytrain stations.", directionalPrice: "Typical guide range: $25–45 budget · $60–120 mid-range · $180+ luxury per night.", baseRange: [25, 120], tierRanges: { hostel: [25, 45], hotel: [60, 120], villaFrom: 180 }, costRank: 2, bestFor: ["solo", "couples", "families"] },
    { key: "silom", name: "Silom", anchor: "#silom", heading: "Central sightseeing and a local city feel", summary: "A business-district base with strong BTS/MRT connections, markets, restaurants, and a convenient position between the river and Sukhumvit.", highlights: ["BTS/MRT interchange", "Markets and rooftop bars", "Central city position"], location: "Central Bangkok", locationContext: "Silom sits centrally between Sukhumvit and the river with both BTS and MRT connections.", directionalPrice: "Typical guide range: $30–50 budget · $65–130 mid-range · $200+ luxury per night.", baseRange: [30, 130], tierRanges: { hostel: [30, 50], hotel: [65, 130], villaFrom: 200 }, costRank: 3, bestFor: ["solo", "couples"] },
    { key: "riverside", name: "Riverside", anchor: "#riverside", heading: "Scenery, temples and a special-stay feel", summary: "A slower riverfront base when boat access, major temples, and hotel atmosphere are part of the trip itself.", highlights: ["Chao Phraya views", "Boat access", "Wat Arun and Grand Palace access"], location: "Chao Phraya riverfront", locationContext: "Riverside follows the Chao Phraya in central Bangkok, with hotel piers and boat access toward major temples.", directionalPrice: "Typical guide range: $35–60 budget · $80–160 mid-range · $250+ luxury per night.", baseRange: [35, 160], tierRanges: { hostel: [35, 60], hotel: [80, 160], villaFrom: 250 }, costRank: 5, bestFor: ["couples", "families"] },
    { key: "khao-san", name: "Khao San Road", anchor: "#khao-san-road", heading: "Budget trips and Old City temples", summary: "A sociable, budget-minded base within walking distance of the Old City temple zone, best for short stays where quiet evenings are not the priority.", highlights: ["Old City temple walks", "Backpacker energy", "Budget accommodation"], location: "Bangkok Old City", locationContext: "Khao San Road sits in Bangkok’s Old City near the main temple and historic-sightseeing zone.", directionalPrice: "Typical guide range: $10–25 budget · $40–80 mid-range · $120+ luxury per night.", baseRange: [10, 80], tierRanges: { hostel: [10, 25], hotel: [40, 80], villaFrom: 120 }, costRank: 1, bestFor: ["solo", "couples"] },
    { key: "sathorn", name: "Sathorn", anchor: "#sathorn", heading: "A quieter, central base", summary: "A more residential and composed central base with BTS and river-ferry connections, suited to longer stays and serviced-apartment-style convenience.", highlights: ["Calmer central setting", "BTS Saphan Taksin", "River ferry access"], location: "Central south Bangkok", locationContext: "Sathorn is south of Silom, close to BTS Saphan Taksin and the river-ferry network.", directionalPrice: "Typical guide range: $30–55 budget · $70–140 mid-range · $210+ luxury per night.", baseRange: [30, 140], tierRanges: { hostel: [30, 55], hotel: [70, 140], villaFrom: 210 }, costRank: 4, bestFor: ["couples", "families"] },
  ],
  scores: {
    vibe: { transit: { sukhumvit: 5, silom: 4, riverside: 2, "khao-san": 1, sathorn: 4 }, temples: { sukhumvit: 1, silom: 3, riverside: 5, "khao-san": 5, sathorn: 3 }, nightlife: { sukhumvit: 5, silom: 4, riverside: 1, "khao-san": 4, sathorn: 2 }, calm: { sukhumvit: 2, silom: 2, riverside: 4, "khao-san": 1, sathorn: 5 } },
    budget: { budget: { sukhumvit: 2, silom: 2, riverside: 1, "khao-san": 5, sathorn: 2 }, mid: { sukhumvit: 4, silom: 4, riverside: 3, "khao-san": 3, sathorn: 4 }, luxury: { sukhumvit: 3, silom: 3, riverside: 5, "khao-san": 1, sathorn: 3 } },
    duration: { short: { sukhumvit: 4, silom: 3, riverside: 3, "khao-san": 4, sathorn: 2 }, medium: { sukhumvit: 4, silom: 4, riverside: 3, "khao-san": 2, sathorn: 4 }, long: { sukhumvit: 3, silom: 3, riverside: 3, "khao-san": 1, sathorn: 5 } },
  },
};

const seoulPeak = (date: string) => [3, 9].includes(Number(date.slice(5, 7)) - 1)
  ? { label: "Seoul peak foliage / blossom reference", multiplier: [1.25, 1.4] as const, note: "The guide notes that April cherry blossoms and October autumn foliage can run 25–40% higher than shoulder-season ranges." }
  : standardSeason("Seoul");

export const seoulStayMatcherConfig: CityMatcherConfig = {
  id: "seoul", city: "Seoul", articleUrl: "/blog/where-to-stay-in-seoul-2026", availabilityUrl: CITY_STAY_MATCHER_AFFILIATE_LINKS.seoul, supportsTierEstimates: false,
  tierNotice: "Localized district room-tier benchmarks are being finalized. Your room type is saved as a preference, but type-specific total estimates are not shown yet.", seasonal: seoulPeak,
  questions: [
    { field: "vibe", label: "What should shape your first Seoul stay?", options: [{ value: "convenience", label: "Central shopping, street food and easy orientation" }, { value: "trend", label: "K-culture, cafés and nightlife" }, { value: "culture", label: "Palaces, teahouses and traditional character" }, { value: "international", label: "International dining and a relaxed rhythm" }] },
    { field: "budget", label: "What is your nightly planning approach?", options: [{ value: "value", label: "Value-led planning" }, { value: "balanced", label: "Balanced convenience" }, { value: "premium", label: "Premium district experience" }] },
    { field: "duration", label: "How long are you likely to stay in Seoul?", options: [{ value: "short", label: "1–3 days" }, { value: "medium", label: "4–7 days" }, { value: "long", label: "8+ days" }] },
  ],
  areas: [
    { key: "myeongdong", name: "Myeongdong", anchor: "#myeongdong", heading: "First-timer convenience, shopping and street food", summary: "A central, tourist-friendly base for an easy first orientation, with dense shopping and street-food activity.", highlights: ["Myeongdong Shopping Street", "Namsan Tower access", "Central subway reach"], location: "Central Seoul", locationContext: "Myeongdong is central Seoul, positioned for straightforward access to city sights and shopping corridors.", directionalPrice: "Typical guide range: $40–160+/night.", baseRange: [40, 160], costRank: 3, bestFor: ["solo", "couples", "families"] },
    { key: "gangnam", name: "Gangnam", anchor: "#gangnam", heading: "Upscale nightlife and K-culture", summary: "A premium south-of-the-river district for luxury shopping, trendy cafés, and an upscale nightlife scene.", highlights: ["COEX Mall", "K-Star Road", "Bongeunsa Temple"], location: "South Seoul", locationContext: "Gangnam is south of the Han River and known for its upscale shopping and nightlife corridors.", directionalPrice: "Typical guide range: $55–200+/night.", baseRange: [55, 200], costRank: 5, bestFor: ["solo", "couples"] },
    { key: "hongdae", name: "Hongdae", anchor: "#hongdae", heading: "Youth culture and better value", summary: "An artsy university district for indie cafés, street performances, nightlife, and a better-value rhythm than Gangnam.", highlights: ["Indie live clubs", "Hongdae Free Market", "Café culture"], location: "North-west Seoul", locationContext: "Hongdae is near Hongik University in north-west Seoul, with an arts and university-led atmosphere.", directionalPrice: "Typical guide range: $30–130+/night.", baseRange: [30, 130], costRank: 1, bestFor: ["solo", "couples"] },
    { key: "itaewon", name: "Itaewon", anchor: "#itaewon", heading: "International and relaxed", summary: "An internationally diverse neighborhood with a wide mix of restaurants, bars, and a more relaxed rhythm than the busiest shopping districts.", highlights: ["International dining", "Leeum Museum", "Namsan Park"], location: "Central Seoul hillside", locationContext: "Itaewon sits centrally below Namsan, known for its international dining and bar scene.", directionalPrice: "Typical guide range: $35–150+/night.", baseRange: [35, 150], costRank: 2, bestFor: ["solo", "couples"] },
    { key: "insadong", name: "Insadong", anchor: "#insadong", heading: "Traditional charm and central location", summary: "A quieter cultural base for teahouses, galleries, antique shops, palaces, and central sightseeing on foot.", highlights: ["Gyeongbokgung Palace", "Bukchon Hanok Village", "Insadong-gil"], location: "Central historic Seoul", locationContext: "Insadong is in central historic Seoul, near palace areas and traditional cultural streets.", directionalPrice: "Typical guide range: $30–140+/night.", baseRange: [30, 140], costRank: 2, bestFor: ["couples", "families"] },
  ],
  scores: { vibe: { convenience: { myeongdong: 5, gangnam: 2, hongdae: 3, itaewon: 2, insadong: 4 }, trend: { myeongdong: 3, gangnam: 5, hongdae: 5, itaewon: 4, insadong: 1 }, culture: { myeongdong: 2, gangnam: 1, hongdae: 2, itaewon: 2, insadong: 5 }, international: { myeongdong: 3, gangnam: 3, hongdae: 3, itaewon: 5, insadong: 2 } }, budget: { value: { myeongdong: 2, gangnam: 1, hongdae: 5, itaewon: 3, insadong: 4 }, balanced: { myeongdong: 4, gangnam: 3, hongdae: 4, itaewon: 4, insadong: 4 }, premium: { myeongdong: 4, gangnam: 5, hongdae: 2, itaewon: 3, insadong: 2 } }, duration: { short: { myeongdong: 5, gangnam: 3, hongdae: 3, itaewon: 3, insadong: 4 }, medium: { myeongdong: 4, gangnam: 3, hongdae: 4, itaewon: 4, insadong: 4 }, long: { myeongdong: 2, gangnam: 3, hongdae: 4, itaewon: 4, insadong: 3 } } },
};

const tokyoPeak = (date: string) => [2, 3, 9, 10].includes(Number(date.slice(5, 7)) - 1)
  ? { label: "Tokyo blossom / foliage reference", multiplier: [1.3, 1.5] as const, note: "The guide notes that late March/early April and October/November can run 30–50% higher than shoulder-season ranges." }
  : standardSeason("Tokyo");

export const tokyoStayMatcherConfig: CityMatcherConfig = {
  id: "tokyo", city: "Tokyo", articleUrl: "/blog/where-to-stay-in-tokyo-2026", availabilityUrl: CITY_STAY_MATCHER_AFFILIATE_LINKS.tokyo, supportsTierEstimates: false,
  tierNotice: "Localized neighborhood room-tier benchmarks are being finalized. Your room type is saved as a preference, but type-specific total estimates are not shown yet.", seasonal: tokyoPeak,
  questions: [
    { field: "vibe", label: "What should shape your first Tokyo stay?", options: [{ value: "transit", label: "Maximum train access and flexibility" }, { value: "trend", label: "Trendy shopping and youthful energy" }, { value: "traditional", label: "Traditional atmosphere and charm" }, { value: "luxury", label: "Luxury dining and premium shopping" }] },
    { field: "budget", label: "What is your nightly planning approach?", options: [{ value: "value", label: "Value-led planning" }, { value: "balanced", label: "Balanced convenience" }, { value: "premium", label: "Premium district experience" }] },
    { field: "duration", label: "How long are you likely to stay in Tokyo?", options: [{ value: "short", label: "1–3 days" }, { value: "medium", label: "4–7 days" }, { value: "long", label: "8+ days" }] },
  ],
  areas: [
    { key: "shinjuku", name: "Shinjuku", anchor: "#shinjuku", heading: "First-timer flexibility, nightlife and transit", summary: "A major-station base for straightforward city-wide train access, entertainment, and a flexible first Tokyo stay.", highlights: ["Major station access", "Golden Gai", "Shinjuku Gyoen"], location: "West-central Tokyo", locationContext: "Shinjuku is a west-central Tokyo rail hub with direct connections across the city.", directionalPrice: "Typical guide range: $50–200+/night.", baseRange: [50, 200], costRank: 3, bestFor: ["solo", "couples", "families"] },
    { key: "shibuya", name: "Shibuya", anchor: "#shibuya", heading: "Trendy shopping and youthful energy", summary: "A camera-ready, high-energy district for shopping, nightlife, the scramble crossing, and easy access toward Harajuku.", highlights: ["Shibuya Sky", "Center Gai", "Harajuku access"], location: "West Tokyo", locationContext: "Shibuya is west of central Tokyo, anchored by its major station, shopping streets, and entertainment area.", directionalPrice: "Typical guide range: $55–210+/night.", baseRange: [55, 210], costRank: 4, bestFor: ["solo", "couples"] },
    { key: "asakusa", name: "Asakusa", anchor: "#asakusa", heading: "Traditional Tokyo and better value", summary: "A more old-Tokyo base for temple areas, traditional streets, and a gentler price point than central entertainment districts.", highlights: ["Senso-ji Temple", "Nakamise Street", "Sumida River"], location: "North-east Tokyo", locationContext: "Asakusa sits in north-east Tokyo beside the Sumida River and the Senso-ji temple area.", directionalPrice: "Typical guide range: $35–150+/night.", baseRange: [35, 150], costRank: 1, bestFor: ["solo", "couples", "families"] },
    { key: "ginza", name: "Ginza", anchor: "#ginza", heading: "Luxury shopping and fine dining", summary: "A polished central base for flagship luxury stores, high-end restaurants, and the city’s most expensive neighborhood positioning.", highlights: ["Ginza Six", "Tsukiji Outer Market", "Imperial Palace access"], location: "Central Tokyo", locationContext: "Ginza is central Tokyo, close to Tokyo Station and the city’s high-end retail and dining streets.", directionalPrice: "Typical guide range: $70–280+/night.", baseRange: [70, 280], costRank: 5, bestFor: ["couples"] },
    { key: "ikebukuro", name: "Ikebukuro", anchor: "#ikebukuro", heading: "Practical, budget-friendly central access", summary: "A major transit hub with stronger value than Shinjuku, suited to travelers who want easy train access without the highest central premium.", highlights: ["Sunshine City", "JR Yamanote Line", "Practical central access"], location: "North-west Tokyo", locationContext: "Ikebukuro is a north-west Tokyo rail hub on the JR Yamanote Line with quick access around the city.", directionalPrice: "Typical guide range: $40–160+/night.", baseRange: [40, 160], costRank: 2, bestFor: ["solo", "families"] },
  ],
  scores: { vibe: { transit: { shinjuku: 5, shibuya: 4, asakusa: 3, ginza: 3, ikebukuro: 5 }, trend: { shinjuku: 4, shibuya: 5, asakusa: 1, ginza: 3, ikebukuro: 2 }, traditional: { shinjuku: 1, shibuya: 1, asakusa: 5, ginza: 2, ikebukuro: 1 }, luxury: { shinjuku: 3, shibuya: 4, asakusa: 1, ginza: 5, ikebukuro: 1 } }, budget: { value: { shinjuku: 2, shibuya: 1, asakusa: 5, ginza: 1, ikebukuro: 4 }, balanced: { shinjuku: 4, shibuya: 3, asakusa: 4, ginza: 2, ikebukuro: 4 }, premium: { shinjuku: 4, shibuya: 4, asakusa: 2, ginza: 5, ikebukuro: 2 } }, duration: { short: { shinjuku: 5, shibuya: 4, asakusa: 3, ginza: 3, ikebukuro: 3 }, medium: { shinjuku: 4, shibuya: 4, asakusa: 4, ginza: 3, ikebukuro: 4 }, long: { shinjuku: 3, shibuya: 2, asakusa: 4, ginza: 2, ikebukuro: 5 } } },
};
