import { Clock3, MapPin } from "lucide-react";
import { useState } from "react";

export const seoulFoodTimelineStops = [
  { time: "10:30", district: "Gwangjang Market · Jongno", title: "Start with market breakfast", budget: "Mayak Gimbap (~₩3,000), Bindaetteok (~₩5,000), or knife-cut noodles (~₩6,000–₩7,000).", cue: "Street-market breakfast" },
  { time: "14:00", district: "Euljiro", title: "Pause for a Hanok or Hipjiro coffee", budget: "Iced Americano or latte: ₩4,500 – ₩6,000; signature pastry or cake: ₩5,500 – ₩7,500.", cue: "Historic cafe interval" },
  { time: "18:30", district: "Hongdae & Sinchon", title: "Choose student-budget BBQ or street snacks", budget: "Street food or casual: ₩4,000 – ₩8,000; BBQ or stews: ₩14,000 – ₩22,000.", cue: "Social dinner stop" },
  { time: "21:00", district: "Gangnam & Cheongdam", title: "Finish with Hanwoo or modern Korean dining", budget: "Fine dining or premium: ₩150,000 – ₩350,000+; a Gangnam coffee: ₩6,500 – ₩8,500.", cue: "Luxury finale" },
] as const;

/** A progressively disclosed Seoul culinary route that keeps the current stop in focus. */
export default function SeoulFoodTimeline() {
  const [activeStop, setActiveStop] = useState(0);
  const stop = seoulFoodTimelineStops[activeStop];
  return (
    <section className="mt-14" aria-labelledby="timeline-title"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0077B6]">Interactive food itinerary</p><h2 id="timeline-title" className="mt-3 font-playfair text-3xl font-bold text-[#0D1B2A]">Gwangjang-to-Gangnam: a Seoul culinary journey</h2><p className="mt-4 max-w-3xl text-lg leading-relaxed text-slate-700">Select each stop to move from a market breakfast through café culture and student dining to a premium Seoul finale.</p><div className="mt-7 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><ol className="space-y-3" aria-label="Food itinerary stops">{seoulFoodTimelineStops.map((item, index) => <li key={item.time}><button type="button" onClick={() => setActiveStop(index)} aria-pressed={activeStop === index} className={`w-full rounded-2xl border p-4 text-left transition ${activeStop === index ? "border-[#0077B6] bg-[#e5f4fb] shadow-sm" : "border-slate-200 bg-white hover:border-[#0077B6]/40"}`}><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#0077B6]"><Clock3 className="h-4 w-4" />{item.time}</span><span className="mt-2 block font-playfair text-xl font-bold text-[#0D1B2A]">{item.district}</span><span className="mt-1 block text-sm text-slate-600">{item.cue}</span></button></li>)}</ol><article className="rounded-3xl bg-[#0D1B2A] p-7 text-white md:p-9"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#F4A261]"><MapPin className="h-4 w-4" />Stop {activeStop + 1} of {seoulFoodTimelineStops.length}</p><h3 className="mt-3 font-playfair text-3xl font-bold">{stop.title}</h3><p className="mt-3 text-sm font-semibold text-[#F4A261]">{stop.district} · {stop.time}</p><p className="mt-6 text-lg leading-relaxed text-slate-200">{stop.budget}</p><div className="mt-8 flex items-center justify-between border-t border-white/15 pt-5"><button type="button" onClick={() => setActiveStop(Math.max(0, activeStop - 1))} disabled={activeStop === 0} className="rounded-full border border-white/30 px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-40">Previous</button><button type="button" onClick={() => setActiveStop(Math.min(seoulFoodTimelineStops.length - 1, activeStop + 1))} disabled={activeStop === seoulFoodTimelineStops.length - 1} className="rounded-full bg-[#F4A261] px-4 py-2 text-sm font-semibold text-[#0D1B2A] disabled:cursor-not-allowed disabled:opacity-40">Next stop</button></div></article></div></section>
  );
}
