import { MoonStar } from "lucide-react";
import { useState } from "react";

export const seoulNightlifeRows = [
  { district: "Hongdae", vibe: "Student-driven, indie rock, EDM, hip-hop, high energy", entry: "Free – ₩15,000 (~$0–$11) (Often includes 1 drink ticket)", drink: "₩4,000 – ₩8,000 (~$3–$6)", supper: "₩5,000 – ₩8,000 (~$3.70–$6) (24h Poiramyeon, Tteokbokki)", vip: "₩150,000 – ₩350,000 (~$110–$260)" },
  { district: "Itaewon", vibe: "International, expat-friendly, rooftop lounge bars, techno", entry: "₩10,000 – ₩20,000 (~$7.50–$15)", drink: "₩9,000 – ₩15,000 (~$6.60–$11)", supper: "₩8,000 – ₩14,000 (~$6–$10.30) (Kebab stalls, slice pizza)", vip: "₩350,000 – ₩650,000 (~$260–$480)" },
  { district: "Gangnam", vibe: "Luxury high-end EDM mega-clubs, lounge bars, VIP culture", entry: "₩20,000 – ₩30,000+ (~$15–$22+)", drink: "₩12,000 – ₩20,000+ (~$9–$15+)", supper: "₩10,000 – ₩18,000 (~$7.50–$13.30) (24h Gukbap / Sundae stew)", vip: "₩650,000 – ₩1,800,000+ (~$480–$1,330+)" },
] as const;

export const seoulNightlifePresets = [
  { name: "Budget Party Night", district: "Hongdae", total: "₩31,000 total (~$23 USD)", detail: "₩10,000 Entry + ₩15,000 Drinks (2 shots/beers) + ₩6,000 Late-Night Snack" },
  { name: "Standard Party Night", district: "Itaewon", total: "₩55,000 total (~$41 USD)", detail: "₩15,000 Entry + ₩30,000 Drinks (3 cocktails) + ₩10,000 Late-Night Kebab" },
  { name: "Premium VIP Night", district: "Gangnam", total: "₩100,000 total (~$74 USD)", detail: "₩25,000 Entry + ₩60,000 Drinks (3 high-end cocktails) + ₩15,000 24h Supper (Excluding VIP bottle service tables)" },
] as const;

export default function SeoulNightlifeBudget() {
  const [activePreset, setActivePreset] = useState(0);
  return <section className="mt-14 rounded-3xl bg-[#0D1B2A] px-6 py-9 text-white md:px-8 md:py-10" aria-labelledby="nightlife-title"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#F4A261]"><MoonStar className="h-4 w-4" />Seoul nightlife budget module</p><h2 id="nightlife-title" className="mt-3 font-playfair text-3xl font-bold">Plan the after-dark part of the trip</h2><p className="mt-4 max-w-3xl leading-relaxed text-slate-200">Compare the supplied 2026 nightlife benchmarks across Hongdae, Itaewon, and Gangnam. Select a party-night setup to keep the total in view.</p><div className="table-responsive mt-7 overflow-x-auto rounded-2xl border border-white/15 bg-white/5"><table className="min-w-[1040px] w-full text-left text-sm"><caption className="sr-only">Seoul nightlife pricing by district.</caption><thead className="bg-white/10 text-[#F4A261]"><tr>{["District", "Primary Nightlife Vibe", "Club Cover / Entry Fee", "Drink / Cocktail Price", "Late-Night Street Food & Supper", "Table / VIP Bottle Service"].map((heading) => <th key={heading} scope="col" className="px-5 py-4 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-white/10 text-slate-100">{seoulNightlifeRows.map((row) => <tr key={row.district} className="align-top"><th scope="row" className="px-5 py-5 font-playfair text-base text-white">{row.district}</th><td className="px-5 py-5 leading-relaxed">{row.vibe}</td><td className="px-5 py-5">{row.entry}</td><td className="px-5 py-5">{row.drink}</td><td className="px-5 py-5">{row.supper}</td><td className="px-5 py-5">{row.vip}</td></tr>)}</tbody></table></div><div className="mt-7 grid gap-3 md:grid-cols-3">{seoulNightlifePresets.map((preset, index) => <button key={preset.name} type="button" onClick={() => setActivePreset(index)} aria-pressed={activePreset === index} className={`rounded-2xl border p-5 text-left transition focus:outline-none focus:ring-2 focus:ring-[#F4A261] focus:ring-offset-2 focus:ring-offset-[#0D1B2A] ${activePreset === index ? "border-[#F4A261] bg-white/12" : "border-white/15 bg-white/5 hover:border-white/35"}`}><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#F4A261]">{preset.district}</p><h3 className="mt-2 font-playfair text-2xl font-bold">{preset.name}</h3><p className="mt-3 font-semibold text-white">{preset.total}</p><p className="mt-2 text-sm leading-relaxed text-slate-200">{preset.detail}</p></button>)}</div><p className="mt-5 text-sm text-slate-300">Selected plan: <span className="font-semibold text-[#F4A261]">{seoulNightlifePresets[activePreset].name}</span>. Always confirm venue age requirements, cover inclusions, and opening hours directly before going out.</p></section>;
}
